"""Tests for CrawlJob domain entity."""

from __future__ import annotations

from datetime import datetime, timedelta, timezone

from scavengarr.domain.entities.crawljob import (
    BooleanStatus,
    CrawlJob,
    Priority,
)


class TestCrawlJobDefaults:
    def test_default_job_id_is_uuid(self) -> None:
        job = CrawlJob()
        assert len(job.job_id) == 36  # UUID4 format
        assert job.job_id.count("-") == 4

    def test_default_package_name(self) -> None:
        job = CrawlJob()
        assert job.package_name == "Scavengarr Download"

    def test_default_auto_start_is_true(self) -> None:
        job = CrawlJob()
        assert job.auto_start == BooleanStatus.TRUE

    def test_default_enabled_is_true(self) -> None:
        job = CrawlJob()
        assert job.enabled == BooleanStatus.TRUE

    def test_default_priority_is_default(self) -> None:
        job = CrawlJob()
        assert job.priority == Priority.DEFAULT

    def test_default_validated_urls_is_empty_list(self) -> None:
        job = CrawlJob()
        assert job.validated_urls == []

    def test_default_extract_passwords_is_empty_list(self) -> None:
        job = CrawlJob()
        assert job.extract_passwords == []

    def test_mutable_defaults_are_independent(self) -> None:
        """Ensure mutable default factories create separate instances."""
        job1 = CrawlJob()
        job2 = CrawlJob()
        job1.validated_urls.append("https://a.com")
        assert job2.validated_urls == []


class TestCrawlJobIsExpired:
    def test_not_expired_when_future(self) -> None:
        future = datetime.now(timezone.utc) + timedelta(hours=1)
        job = CrawlJob(expires_at=future)
        assert job.is_expired() is False

    def test_expired_when_past(self) -> None:
        past = datetime.now(timezone.utc) - timedelta(hours=1)
        job = CrawlJob(expires_at=past)
        assert job.is_expired() is True


class TestCrawlJobToCrawljobFormat:
    def test_contains_core_fields(self, crawljob: CrawlJob) -> None:
        output = crawljob.to_crawljob_format()
        assert "text=https://example.com/download/1" in output
        assert "packageName=Iron.Man.2008" in output

    def test_contains_behavior_flags(self, crawljob: CrawlJob) -> None:
        output = crawljob.to_crawljob_format()
        assert "autoStart=TRUE" in output
        assert "enabled=TRUE" in output
        assert "autoConfirm=UNSET" in output

    def test_contains_download_config(self, crawljob: CrawlJob) -> None:
        output = crawljob.to_crawljob_format()
        assert "chunks=0" in output
        assert "priority=DEFAULT" in output
        assert "deepAnalyseEnabled=false" in output
        assert "addOfflineLink=true" in output

    def test_optional_filename_included_when_set(self) -> None:
        job = CrawlJob(filename="movie.mkv")
        output = job.to_crawljob_format()
        assert "filename=movie.mkv" in output

    def test_optional_filename_omitted_when_none(self) -> None:
        job = CrawlJob(filename=None)
        output = job.to_crawljob_format()
        assert "filename=" not in output

    def test_comment_included_when_set(self) -> None:
        job = CrawlJob(comment="test comment")
        output = job.to_crawljob_format()
        assert "comment=test comment" in output

    def test_extract_passwords_json_format(self) -> None:
        job = CrawlJob(extract_passwords=["pass1", "pass2"])
        output = job.to_crawljob_format()
        assert 'extractPasswords=["pass1","pass2"]' in output

    def test_extract_passwords_special_characters(self) -> None:
        """Passwords with quotes/backslashes must be JSON-escaped."""
        job = CrawlJob(extract_passwords=['p"ass', "back\\slash"])
        output = job.to_crawljob_format()
        assert r'extractPasswords=["p\"ass","back\\slash"]' in output

    def test_extract_passwords_omitted_when_empty(self) -> None:
        job = CrawlJob(extract_passwords=[])
        output = job.to_crawljob_format()
        assert "extractPasswords=" not in output

    def test_download_password_included_when_set(self) -> None:
        job = CrawlJob(download_password="secret")
        output = job.to_crawljob_format()
        assert "downloadPassword=secret" in output

    def test_header_comments(self, crawljob: CrawlJob) -> None:
        output = crawljob.to_crawljob_format()
        assert output.startswith("# Generated by Scavengarr")
        assert "# Job ID: test-job-id-123" in output


class TestEnums:
    def test_boolean_status_values(self) -> None:
        assert BooleanStatus.TRUE.value == "TRUE"
        assert BooleanStatus.FALSE.value == "FALSE"
        assert BooleanStatus.UNSET.value == "UNSET"

    def test_priority_values(self) -> None:
        assert Priority.HIGHEST.value == "HIGHEST"
        assert Priority.DEFAULT.value == "DEFAULT"
        assert Priority.LOWER.value == "LOWER"
