"""Generate docs/plugins.md from the plugin metadata.

Usage:
    poetry run python scripts/generate_plugin_list.py           # rewrite the file
    poetry run python scripts/generate_plugin_list.py --check   # exit 1 if outdated

The list is generated, not written by hand, so it cannot drift from the
plugins: ``tests/unit/infrastructure/test_plugin_list_doc.py`` fails when
``docs/plugins.md`` differs from the output of :func:`render`.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from scavengarr.infrastructure.plugins.registry import PluginRegistry

_ROOT = Path(__file__).resolve().parents[1]
_OUT = _ROOT / "docs" / "plugins.md"

_PROVIDES = {
    "stream": "Streams",
    "download": "Downloads",
    "both": "Streams + downloads",
}
_ENGINES = {"httpx": "httpx", "playwright": "Playwright"}

_HEADER = """\
[← Back to README](../README.md)

# Plugins

<!-- Generated by scripts/generate_plugin_list.py, do not edit by hand. -->

> **Disclaimer:** Scavengarr does not host, store or distribute any content.
> Plugins only read what the listed websites publish themselves. You are
> responsible for complying with the laws of your country and the terms of
> the sites you use; use Scavengarr only for content you are allowed to access.

Every plugin is a Python file in [`plugins/`](../plugins) and can be added
to Prowlarr as a Torznab indexer (`/api/v1/torznab/<plugin>`). *Content*
says what a site offers: *Streams* are streaming hoster links; these plugins
also feed the Stremio addon, which resolves the links to playable video.
*Downloads* are direct-download links (validated, optionally bundled as a
JDownloader `.crawljob`) and are only served via Torznab. *Engine* is
`httpx` for static HTML and APIs, `Playwright` for sites that need a real
browser. *Mirrors* counts the extra domains tried when the primary one
is unreachable.

"""


def _collect(plugin_dir: Path) -> list[tuple[str, str, int, str, str, str]]:
    registry = PluginRegistry(plugin_dir)
    rows = []
    for name in registry.list_names():
        plugin = registry.get(name)
        domains = list(getattr(plugin, "_domains", []) or [])
        rows.append(
            (
                name,
                domains[0] if domains else "",
                max(len(domains) - 1, 0),
                _PROVIDES.get(str(getattr(plugin, "provides", "")), "?"),
                _ENGINES.get(registry.get_mode(name), registry.get_mode(name)),
                ", ".join(registry.get_languages(name)),
            )
        )
    return rows


def render(plugin_dir: Path) -> str:
    """Return the complete Markdown for ``docs/plugins.md``."""
    rows = _collect(plugin_dir)
    streams = sum("Streams" in r[3] for r in rows)
    downloads = sum("ownloads" in r[3] for r in rows)
    lines = [
        _HEADER.rstrip("\n"),
        "",
        f"{len(rows)} plugins: {streams} with streams (used by the Stremio "
        f"addon), {downloads} with direct downloads.",
        "",
        "| Plugin | Website | Mirrors | Content | Engine | Languages |",
        "|---|---|---|---|---|---|",
    ]
    for name, domain, mirrors, provides, engine, languages in rows:
        lines.append(
            f"| `{name}` | {domain} | {mirrors} | {provides} | {engine} | {languages} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="exit 1 if docs/plugins.md is outdated"
    )
    args = parser.parse_args()

    text = render(_ROOT / "plugins")
    if args.check:
        current = _OUT.read_text(encoding="utf-8") if _OUT.exists() else ""
        if current != text:
            print("docs/plugins.md is outdated", file=sys.stderr)
            return 1
        return 0
    _OUT.write_text(text, encoding="utf-8")
    print(f"wrote {_OUT.relative_to(_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
